name: Build all platforms

on:
  workflow_dispatch:
  push:
    branches:
      - 'gh-actions'
    
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-build.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install build dependencies
        run: pip install -r requirements-build.txt

      - name: Build artifacts
        run: python -m nuitka --standalone --assume-yes-for-downloads --follow-imports --enable-plugin=pyside6 --lto=no vfl2csv_forms

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: 'vfl2csv_forms.dist/'
